name: Access ID Workflow

on:
  push:

jobs:
  print-access-id:
    runs-on: ubuntu-latest
    steps:
      - name: Print ACCESS_ID
        run: echo "The ACCESS_ID is $ACCESS_ID"
        env:
          ACCESS_ID: ${{ vars.ACCESS_ID }}

